### ISSUE TITLE
Some post-use feedback.

### ISSUE THREAD

**Issue by wzhchin** [euclio/fm#54] opened 2023-05-18 07:46 UTC
Thank you for creating such a great software. However, I have noticed some inconveniences while using it:

  1.  ~~The lack of support for some shortcut keys, such as pressing the right arrow key to jump to the next level directory and the left arrow key to jump to the parent directory.~~ This is a duplicate of issue #3
   2. It would be helpful if the software automatically focused on the leftmost directory upon startup.
   3. Necessary search support is needed when there are many files in a particular directory. 
   4. It would also be beneficial if the top bar displayed the current path.

I look forward to your response.

**Comment by euclio** [comment] 2023-05-18 17:02
Hi, thanks for trying it out! I haven't actually had an official release yet, so consider this "alpha software" not really intended for use yet :)

I think 4 is a duplicate of #19. Mind creating separate issues for the other two? Happy to look into them.

**Closed as completed by euclio** 2023-05-18 17:02 UTC
